# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: notification-deployment
serviceName: notification-service
appLabel: notification-service
appName: notification-service

replicaCount: 1

image:
  repository: robert111/notification
  tag: s1

containerPort: 8040

service:
  type: ClusterIP
  port: 8040
  targetPort: 8040

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
kafka_enabled: true
mongodb_enabled: false
postgres_config: false