spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: "http://keycloak-ms:8080/realms/micro-services"
          jwk-set-uri: "http://keycloak-ms:8080/realms/micro-services/protocol/openid-connect/certs"
  config:
    import: optional:configserver:http://config-server-ms:8888
  application:
    name: gateway-service

#logging:
  #level:
    #org.springframework.cloud.gateway: DEBUG

