# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: product-deployment
serviceName: product-service
appLabel: product-service
appName: product-service

replicaCount: 1

image:
  repository: robert111/product
  tag: s1

containerPort: 8050

service:
  type: ClusterIP
  port: 8050
  targetPort: 8050

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
kafka_enabled: false
mongodb_enabled: false
postgres_config: false