{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
            {{- if .Values.mail_dev_enabled }}
            - containerPort: 1080
              protocol: TCP
            {{- end }}
            {{- if .Values.kafka_config }}
            - containerPort: 9093
              protocol: TCP
            {{- end }}
          {{- if .Values.kafka_config }}
          volumes:
            - name: kafka_data:/bitnami
              size: "1Gi"
          {{- end }}
          env:
          {{- if .Values.mongodb_enabled }}
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.global.mongodbUsername }}
          {{- end }}
          {{- if .Values.mongodb_enabled }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.global.mongodbUsername }}
          {{- end }}
          {{- if .Values.mongodb_enabled }}
          - name: SPRING_DATA_MONGODB_URI
            value: {{ .Values.global.SPRING_DATA_MONGODB_URI }}
          {{- end }}
          {{- if .Values.appname_enabled }}
          - name: SPRING_APPLICATION_NAME
            value: {{ .Values.appName }}
          {{- end }}
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILES_ACTIVE
          {{- end }}
          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CONFIG_IMPORT
          {{- end }}
          {{- if .Values.eureka_enabled }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          {{- end }}
          {{- if .Values.resouceserver_enabled }}
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          {{- end }}
          {{- if .Values.kafka_enabled }}
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          {{- end }}
          {{- if .Values.postgres_config }}
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: POSTGRES_PASSWORD
          - name: PGDATA
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: PGDATA
          {{- end }}
          {{- if .Values.pgadmin_config }}
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: PGADMIN_DEFAULT_EMAIL
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: PGADMIN_DEFAULT_PASSWORD
          - name: PGADMIN_CONFIG_SERVER_MODE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: PGADMIN_CONFIG_SERVER_MODE
          {{- end }}
          {{- if .Values.kafka_config }}
          - name: KAFKA_CFG_NODE_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_NODE_ID
          - name: KAFKA_CFG_PROCESS_ROLES
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_PROCESS_ROLES
          - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          - name: KAFKA_CFG_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_LISTENERS
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_ADVERTISED_LISTENERS
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          {{- end }}
{{- end -}}