spring:
  config:
    import: optional:configserver:http://config-server-ms:8888
  application:
    name: discovery
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
      endpoint:
        health:
          probes:
            enabled: true