# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: order-deployment
serviceName: order-service
appLabel: order-service
appName: order-service

replicaCount: 1

image:
  repository: robert111/order
  tag: s1

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
kafka_enabled: true
mongodb_enabled: false
postgres_config: false