apiVersion: v1
kind: ConfigMap
metadata:
  name: robert111-configmap
data:
  SPRING_CONFIG_IMPORT: "configserver:http://config-server-ms:8888/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery:8761/eureka/"
  CONFIG_SERVER_APPLICATION_NAME: "config-server"
  EUREKA_APPLICATION_NAME: "discovery-service"
  ORDER_APPLICATION_NAME: "order-service"
  CUSTOMER_APPLICATION_NAME: "customer-service"
  PRODUCT_APPLICATION_NAME: "product-service"
  PAYMENT_APPLICATION_NAME: "payment-service"
  GATEWAY_APPLICATION_NAME: "gateway-service"
  NOTIFICATION_APPLICATION_NAME: "notification-service"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak-ms:8080/realms/micro-services/protocol/openid-connect/certs"