# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: payment-deployment
serviceName: payment-service
appLabel: payment-service
appName: payment-service

replicaCount: 1

image:
  repository: robert111/payment
  tag: s1

containerPort: 8060

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
kafka_enabled: true
mongodb_enabled: false
postgres_config: false